language: php

sudo: required

cache:
  directories:
      - vendor
      - $HOME/.composer/cache
      - bin/.phpunit

php:
  - 7.2

env:
  # plugin code
  global:
    PLUGIN_CODE=Coupon
    BRANCH=experimental/sf

before_install: &php_setup |
  phpenv config-rm xdebug.ini || true
  echo "opcache.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install_eccube: &install_eccube |
  tar cvzf ${HOME}/${PLUGIN_CODE}.tar.gz ./*
  git clone https://github.com/EC-CUBE/ec-cube.git
  cd ec-cube
  git checkout -b ${BRANCH} origin/${BRANCH}
  composer selfupdate
  composer install --dev --no-interaction -o --apcu-autoloader

eccube_setup: &eccube_setup |
  echo "APP_ENV=test" > .env
  bin/console doctrine:database:create
  bin/console doctrine:schema:create
  bin/console eccube:fixtures:load
  bin/console eccube:plugin:install --path=${HOME}/${PLUGIN_CODE}.tar.gz
  bin/console eccube:plugin:enable --code=${PLUGIN_CODE}

jobs:
  fast_finish: true
  include:
    - stage: Inspection
      php: 7.1
      env: DATABASE_URL=postgres://postgres:password@localhost/cube4_dev DATABASE_SERVER_VERSION=9
      install:
        - *install_eccube
        - *eccube_setup
      script: vendor/bin/php-cs-fixer fix --config=.php_cs.dist --dry-run app/Plugin/${PLUGIN_CODE}
    - &unit_test
      stage: Unit Test
      env: DATABASE_URL=mysql://root:@localhost/cube4_dev DATABASE_SERVER_VERSION=5
      before_install:
        - *php_setup
        - gem install mime-types -v 2.99.1
        - gem install mailcatcher
      install:
        - *install_eccube
        - *eccube_setup
        # mail catcher
        - mailcatcher
      script:
        - ./bin/phpunit app/Plugin/${PLUGIN_CODE}/Tests
      after_script:
        # disable plugin
        - bin/console eccube:plugin:disable --code=${PLUGIN_CODE}
        # uninstall plugin
        - bin/console eccube:plugin:uninstall --code=${PLUGIN_CODE}
        # re install plugin
        - bin/console eccube:plugin:install --code=${PLUGIN_CODE}
        # re enable plugin
        - bin/console eccube:plugin:enable --code=${PLUGIN_CODE}
    - <<: *unit_test
      env: DATABASE_URL=postgres://postgres:password@localhost/cube4_dev DATABASE_SERVER_VERSION=9
    - &coverage
      stage: Code Coverage
      env: DATABASE_URL=postgres://postgres:password@localhost/cube4_dev DATABASE_SERVER_VERSION=9 COVERAGE=1
      before_install:
        - *php_setup
        - gem install mime-types -v 2.99.1
        - gem install mailcatcher
      install:
        - *install_eccube
        - *eccube_setup
        # mail catcher
        - mailcatcher
      script:
        - ./bin/phpunit -c app/Plugin/${PLUGIN_CODE}/phpunit.xml.dist --coverage-clover=coverage.clover
      after_success:
        - php vendor/bin/php-coveralls -v -x coverage.clover
