<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Coupon4\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\Coupon4\Entity\CouponDetail;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * CouponDetailRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponDetailRepository extends AbstractRepository
{
    /**
     * CouponDetailRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, CouponDetail::class);
    }
}
