<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * https://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Coupon44\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Entity\AbstractEntity;
use Eccube\Repository\AbstractRepository;
use Plugin\Coupon44\Entity\CouponOrder;

/**
 * CouponOrderRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<CouponOrder>
 */
class CouponOrderRepository extends AbstractRepository
{
    /**
     * CouponOrderRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, CouponOrder::class);
    }

    /**
     * クーポン受注情報を保存する.
     *
     * 本体の AbstractRepository::save() は persist のみだが、呼び出し側
     * (CouponService::saveCouponOrder 等) は save() 後に flush しないため、
     * ここで flush まで行う。シグネチャは親と互換にする。
     *
     * @param CouponOrder $CouponOrder
     */
    public function save(AbstractEntity $CouponOrder): void
    {
        $em = $this->getEntityManager();
        $em->persist($CouponOrder);
        $em->flush();
    }

    /**
     * 会員または非会員が既にクーポンを利用しているか検索
     * 会員の場合、会員IDで非会員の場合、メールアドレスで検索.
     *
     * @param string $couponCd
     * @param int|string|null $param 会員IDまたはメールアドレス
     *
     * @return array<int, CouponOrder>
     */
    public function findUseCoupon(string $couponCd, int|string|null $param): array
    {
        $userId = null;
        $email = null;

        if (is_numeric($param)) {
            $userId = $param;
        } else {
            $email = $param;
        }

        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.coupon_cd = :coupon_cd')
            ->andWhere('c.order_date IS NOT NULL')
            ->andWhere('c.user_id = :user_id OR c.email = :email')
            ->setParameter('coupon_cd', $couponCd)
            ->setParameter('user_id', $userId)
            ->setParameter('email', $email);
        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }

    /**
     * クーポン受注情報を取得する.
     *
     * @param string $preOrderId
     *
     * @return CouponOrder|null
     */
    public function getCouponOrder(string $preOrderId): ?CouponOrder
    {
        $CouponOrder = $this->findOneBy([
            'pre_order_id' => $preOrderId,
        ]);

        return $CouponOrder;
    }
}
